server:
    port: 9093
    address: 0.0.0.0

spring:
    datasource:
#       url: jdbc:mysql://172.17.0.1:3306/jf203?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        url: jdbc:mysql://localhost:3306/jf203?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    type-aliases-package: online.jf203.bean

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false